# application properties
title: "SSH Poweroff"
port: 8081
mail: "mail@example.com"
log-path: "/var/log/ssh-poweroff/sshpoff.log"

# devices properties (DO NOT USE TABS)
devices:
  - name: "Device 1"
    host: "255.255.255.255"
    port: 22
    user: "root"
    password: "toor"
    command: "halt"
  - name: "Device 2"
    host: "255.255.255.255"
    port: 22
    user: "root"
    password: "toor"
    command: "halt"

# button messages
poweroff-all: "Power off all devices!"

# error/success messages
# {} is replaced with device name
success-msg: "{} successfully turned off."
unvalid-msg: "{} is not valid!"
no-ssh-msg: "Could not communicate with {}!"
